In [9]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from app.ml.preprocessing import preprocess

In [10]:
DATASET_PATH = "../data/generated/customer_support_dataset.csv"

df = pd.read_csv(DATASET_PATH)

df.head()

,customer_name,customer_email,customer_type,country,channel,product,ticket_id,subject,description,category,priority,sentiment,assigned_team,status
0,Clinton Nichols,alexanderharmon@example.org,Enterprise,Canada,Chat,API Platform,TKT-DD82610CA0,Organization details incorrect,I have been trying to access my account since ...,Account,Medium,Negative,Account Support Team,Open
1,Michael Lopez,matthew78@example.org,Premium,Canada,Phone,Web Dashboard,TKT-132439D31D,Reset code invalid,I have been trying to access my account since ...,Password Reset,Medium,Negative,Authentication Team,Open
2,Megan Garcia,brookserika@example.org,Enterprise,Brazil,Website,Reporting Engine,TKT-0B7E32F4C9,Business profile issue,I have been trying to access my account since ...,Account,Low,Neutral,Account Support Team,Open
3,Debra Garcia,kathryn26@example.org,Enterprise,India,Mobile App,Web Dashboard,TKT-F837AEB837,Login failed,I have been trying to access my account since ...,Login,Medium,Negative,Authentication Team,Open
4,Kristen Morris,veronicagonzales@example.net,Free,United Kingdom,Mobile App,CRM Suite,TKT-604F417304,Password reset page not working,I have been trying to access my account since ...,Password Reset,Medium,Neutral,Authentication Team,Open

In [11]:
df["processed_description"] = df["description"].apply(preprocess)
df.head()

,customer_name,customer_email,customer_type,country,channel,product,ticket_id,subject,description,category,priority,sentiment,assigned_team,status,processed_description
0,Clinton Nichols,alexanderharmon@example.org,Enterprise,Canada,Chat,API Platform,TKT-DD82610CA0,Organization details incorrect,I have been trying to access my account since ...,Account,Medium,Negative,Account Support Team,Open,trying access account since yesterday using go...
1,Michael Lopez,matthew78@example.org,Premium,Canada,Phone,Web Dashboard,TKT-132439D31D,Reset code invalid,I have been trying to access my account since ...,Password Reset,Medium,Negative,Authentication Team,Open,trying access account since today using google...
2,Megan Garcia,brookserika@example.org,Enterprise,Brazil,Website,Reporting Engine,TKT-0B7E32F4C9,Business profile issue,I have been trying to access my account since ...,Account,Low,Neutral,Account Support Team,Open,trying access account since yesterday using mo...
3,Debra Garcia,kathryn26@example.org,Enterprise,India,Mobile App,Web Dashboard,TKT-F837AEB837,Login failed,I have been trying to access my account since ...,Login,Medium,Negative,Authentication Team,Open,trying access account since yesterday using mo...
4,Kristen Morris,veronicagonzales@example.net,Free,United Kingdom,Mobile App,CRM Suite,TKT-604F417304,Password reset page not working,I have been trying to access my account since ...,Password Reset,Medium,Neutral,Authentication Team,Open,trying access account since last two day using...

In [12]:
vectorizer = TfidfVectorizer(
    max_features=5000
)

X = vectorizer.fit_transform(
    df["processed_description"]
)

In [13]:
print(X.shape)

(1000, 122)

In [14]:
encoder = LabelEncoder()

y = encoder.fit_transform(df["category"])

In [15]:
print(encoder.classes_)

['Account' 'Login' 'Password Reset']

In [16]:
print(y[:10])

[0 2 0 1 2 2 0 2 1 1]

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [18]:
print("Training")

print(X_train.shape)

print()

print("Testing")

print(X_test.shape)

Training
(800, 122)

Testing
(200, 122)